declare const runtimeGenerationBrand: unique symbol;
export type RuntimeGeneration = Readonly<{ readonly generation: number; readonly [runtimeGenerationBrand]: "RuntimeGeneration" }>;
export interface RuntimeLiveFence { readonly generation: number; readonly live: boolean; capture(): RuntimeGeneration; accepts(generation: RuntimeGeneration): boolean; stop(): void; }
export type MailboxAdmissionResult = Readonly<{ status: "accepted" | "overflow" | "fenced" | "stopped"; size: number }>;
export interface MailboxTelemetry { readonly capacity: number; readonly size: number; readonly acceptedCount: number; readonly overflowCount: number; readonly fencedCount: number; readonly stoppedCount: number; readonly drainedCount: number; readonly clearedCount: number; readonly live: boolean; readonly generation: number; }
export interface BoundedMailbox<Input, Snapshot> { readonly capacity: number; readonly size: number; enqueue(value: Input, generation: RuntimeGeneration): MailboxAdmissionResult; drainPhase(): readonly Snapshot[]; clear(): number; stop(): void; inspect(): MailboxTelemetry; }
export interface CreateBoundedMailboxOptions<Input, Snapshot> { readonly capacity: number; readonly fence: RuntimeLiveFence; readonly copySnapshot: (value: Input) => Snapshot; }
class LiveFence implements RuntimeLiveFence { private isLive = true; private readonly token: RuntimeGeneration; constructor(readonly generation: number) { this.token = Object.freeze({ generation }) as RuntimeGeneration; } get live(): boolean { return this.isLive; } capture(): RuntimeGeneration { return this.token; } accepts(generation: RuntimeGeneration): boolean { return this.isLive && generation === this.token; } stop(): void { this.isLive = false; } }
function increment(value: number, amount: number, name: string): number { const next = value + amount; if (!Number.isSafeInteger(next)) throw new Error(name + " safe-integer counter overflow"); return next; }
class Mailbox<Input, Snapshot> implements BoundedMailbox<Input, Snapshot> { private readonly queue: Snapshot[] = []; private stopped = false; private acceptedCount = 0; private overflowCount = 0; private fencedCount = 0; private stoppedCount = 0; private drainedCount = 0; private clearedCount = 0; constructor(readonly capacity: number, private readonly fence: RuntimeLiveFence, private readonly copySnapshot: (value: Input) => Snapshot) {} get size(): number { return this.queue.length; } enqueue(value: Input, generation: RuntimeGeneration): MailboxAdmissionResult { if (this.stopped) { this.stoppedCount = increment(this.stoppedCount, 1, "mailbox stopped"); return Object.freeze({ status: "stopped", size: this.queue.length }); } if (!this.fence.accepts(generation)) { this.fencedCount = increment(this.fencedCount, 1, "mailbox fenced"); return Object.freeze({ status: "fenced", size: this.queue.length }); } if (this.queue.length === this.capacity) { this.overflowCount = increment(this.overflowCount, 1, "mailbox overflow"); return Object.freeze({ status: "overflow", size: this.queue.length }); } const snapshot = this.copySnapshot(value); this.queue.push(snapshot); this.acceptedCount = increment(this.acceptedCount, 1, "mailbox accepted"); return Object.freeze({ status: "accepted", size: this.queue.length }); } drainPhase(): readonly Snapshot[] { const drained = this.queue.splice(0, this.queue.length); this.drainedCount = increment(this.drainedCount, drained.length, "mailbox drained"); return Object.freeze(drained); } clear(): number { const count = this.queue.length; this.queue.length = 0; this.clearedCount = increment(this.clearedCount, count, "mailbox cleared"); return count; } stop(): void { this.stopped = true; } inspect(): MailboxTelemetry { return Object.freeze({ capacity: this.capacity, size: this.queue.length, acceptedCount: this.acceptedCount, overflowCount: this.overflowCount, fencedCount: this.fencedCount, stoppedCount: this.stoppedCount, drainedCount: this.drainedCount, clearedCount: this.clearedCount, live: !this.stopped && this.fence.live, generation: this.fence.generation }); } }
export function createRuntimeLiveFence(generation = 1): RuntimeLiveFence { if (!Number.isSafeInteger(generation) || generation < 0) throw new TypeError("Runtime generation must be a non-negative safe integer"); return new LiveFence(generation); }
export function createBoundedMailbox<Input, Snapshot>(options: CreateBoundedMailboxOptions<Input, Snapshot>): BoundedMailbox<Input, Snapshot> { if (!Number.isSafeInteger(options.capacity) || options.capacity < 0) throw new TypeError("Mailbox capacity must be a non-negative safe integer"); if (typeof options.copySnapshot !== "function") throw new TypeError("Mailbox copySnapshot must be a function"); return new Mailbox(options.capacity, options.fence, options.copySnapshot); }
