export interface GenreVector3 { readonly x: number; readonly y: number; readonly z: number; }

function id(value: string, label: string): string {
  if (typeof value !== "string" || value.length === 0 || value.length > 128 || value.trim() !== value) throw new TypeError(`${label} must be a trimmed non-empty string of at most 128 characters`);
  return value;
}
function number(value: number, label: string): number { if (typeof value !== "number" || !Number.isFinite(value)) throw new TypeError(`${label} must be finite`); return value; }
function positive(value: number, label: string): number { const result = number(value, label); if (result <= 0) throw new TypeError(`${label} must be positive`); return result; }
function tick(value: number, label: string): number { if (!Number.isSafeInteger(value) || value < 0) throw new TypeError(`${label} must be a non-negative safe integer`); return value; }
function vector(value: GenreVector3, label: string): GenreVector3 {
  if (typeof value !== "object" || value === null || Array.isArray(value) || Reflect.ownKeys(value).sort().join("|") !== "x|y|z") throw new TypeError(`${label} must contain exactly x, y, and z`);
  return Object.freeze({ x: number(value.x, `${label}.x`), y: number(value.y, `${label}.y`), z: number(value.z, `${label}.z`) });
}
function compare(left: string, right: string): number { return left < right ? -1 : left > right ? 1 : 0; }
function active(disposed: boolean, label: string): void { if (disposed) throw new Error(`${label} has been disposed`); }

// General Physics: deterministic AABB reference backend behind a vendor-neutral contract.
export interface PhysicsBodyDefinition {
  readonly id: string;
  readonly kind: "static" | "dynamic" | "kinematic";
  readonly position: GenreVector3;
  readonly halfExtents: GenreVector3;
  readonly velocity?: GenreVector3;
  readonly mass?: number;
  readonly gravityScale?: number;
  readonly layer?: number;
  readonly mask?: number;
  readonly sensor?: boolean;
}
export interface PhysicsBodyState extends Omit<PhysicsBodyDefinition, "velocity" | "mass" | "gravityScale" | "layer" | "mask" | "sensor"> {
  readonly velocity: GenreVector3; readonly mass: number; readonly gravityScale: number; readonly layer: number; readonly mask: number; readonly sensor: boolean;
}
export interface PhysicsContactEvent { readonly kind: "enter" | "stay" | "exit"; readonly bodyAId: string; readonly bodyBId: string; readonly sensor: boolean; readonly tick: number; }
export interface PhysicsRayHit { readonly bodyId: string; readonly distance: number; readonly point: GenreVector3; }
export interface GeneralPhysicsInspection { readonly disposed: boolean; readonly bodies: readonly PhysicsBodyState[]; readonly activeContactCount: number; readonly stepCount: number; }
export interface GeneralPhysicsRuntime {
  readonly disposed: boolean;
  addBody(definition: PhysicsBodyDefinition): PhysicsBodyState;
  removeBody(bodyId: string): boolean;
  applyForce(bodyId: string, force: GenreVector3): void;
  applyImpulse(bodyId: string, impulse: GenreVector3): void;
  setKinematicPosition(bodyId: string, position: GenreVector3): void;
  step(stepTick: number, dtSeconds: number): readonly PhysicsContactEvent[];
  raycast(origin: GenreVector3, direction: GenreVector3, maximumDistance: number, mask?: number): PhysicsRayHit | undefined;
  overlapBox(center: GenreVector3, halfExtents: GenreVector3, mask?: number): readonly string[];
  inspect(): GeneralPhysicsInspection;
  dispose(): void;
}
type Body = { definition: PhysicsBodyDefinition; position: GenreVector3; velocity: GenreVector3; force: GenreVector3 };
function bits(value: number | undefined, fallback: number, label: string): number { const result = value ?? fallback; if (!Number.isSafeInteger(result) || result < 0 || result > 0x7fffffff) throw new TypeError(`${label} must be a non-negative 31-bit integer`); return result; }
function bodyState(body: Body): PhysicsBodyState {
  const d = body.definition;
  return Object.freeze({ id: d.id, kind: d.kind, position: vector(body.position, "Physics position"), halfExtents: d.halfExtents, velocity: vector(body.velocity, "Physics velocity"), mass: d.mass ?? 1, gravityScale: d.gravityScale ?? 1, layer: d.layer ?? 1, mask: d.mask ?? 0x7fffffff, sensor: d.sensor ?? false });
}
function overlap(a: Body, b: Body): boolean { return Math.abs(a.position.x - b.position.x) <= a.definition.halfExtents.x + b.definition.halfExtents.x && Math.abs(a.position.y - b.position.y) <= a.definition.halfExtents.y + b.definition.halfExtents.y && Math.abs(a.position.z - b.position.z) <= a.definition.halfExtents.z + b.definition.halfExtents.z; }
export function createGeneralPhysicsRuntime(options: Readonly<{ readonly gravity?: GenreVector3 }> = {}): GeneralPhysicsRuntime {
  if (typeof options !== "object" || options === null || Array.isArray(options) || !Reflect.ownKeys(options).every((key) => key === "gravity")) throw new TypeError("General Physics options are invalid");
  const gravity = vector(options.gravity ?? { x: 0, y: -9.81, z: 0 }, "Physics gravity");
  const bodies = new Map<string, Body>(); let contacts = new Map<string, { a: string; b: string; sensor: boolean }>(); let stepCount = 0; let disposed = false;
  function requireBody(rawId: string): Body { const key = id(rawId, "Physics body ID"); const body = bodies.get(key); if (body === undefined) throw new RangeError(`Unknown physics body: ${key}`); return body; }
  const runtime = Object.freeze<GeneralPhysicsRuntime>({
    get disposed() { return disposed; },
    addBody(raw): PhysicsBodyState {
      active(disposed, "General Physics runtime");
      if (typeof raw !== "object" || raw === null || Array.isArray(raw) || !["static", "dynamic", "kinematic"].includes(raw.kind)) throw new TypeError("Physics body definition is invalid");
      const bodyId = id(raw.id, "Physics body ID"); if (bodies.has(bodyId)) throw new TypeError(`Duplicate physics body: ${bodyId}`);
      const halfExtents = vector(raw.halfExtents, "Physics halfExtents"); if (halfExtents.x <= 0 || halfExtents.y <= 0 || halfExtents.z <= 0) throw new TypeError("Physics halfExtents must be positive");
      const mass = positive(raw.mass ?? 1, "Physics mass"); const definition = Object.freeze({ ...raw, id: bodyId, position: vector(raw.position, "Physics position"), halfExtents, velocity: vector(raw.velocity ?? { x: 0, y: 0, z: 0 }, "Physics velocity"), mass, gravityScale: number(raw.gravityScale ?? 1, "Physics gravityScale"), layer: bits(raw.layer, 1, "Physics layer"), mask: bits(raw.mask, 0x7fffffff, "Physics mask"), sensor: raw.sensor ?? false });
      if (typeof definition.sensor !== "boolean") throw new TypeError("Physics sensor must be boolean");
      const record = { definition, position: definition.position, velocity: definition.velocity, force: Object.freeze({ x: 0, y: 0, z: 0 }) }; bodies.set(bodyId, record); return bodyState(record);
    },
    removeBody(rawId): boolean { active(disposed, "General Physics runtime"); const bodyId = id(rawId, "Physics body ID"); const removed = bodies.delete(bodyId); if (removed) for (const [key, pair] of contacts) if (pair.a === bodyId || pair.b === bodyId) contacts.delete(key); return removed; },
    applyForce(rawId, rawForce): void { active(disposed, "General Physics runtime"); const body = requireBody(rawId); if (body.definition.kind !== "dynamic") throw new TypeError("Forces require a dynamic body"); const force = vector(rawForce, "Physics force"); body.force = Object.freeze({ x: body.force.x + force.x, y: body.force.y + force.y, z: body.force.z + force.z }); },
    applyImpulse(rawId, rawImpulse): void { active(disposed, "General Physics runtime"); const body = requireBody(rawId); if (body.definition.kind !== "dynamic") throw new TypeError("Impulses require a dynamic body"); const impulse = vector(rawImpulse, "Physics impulse"); const mass = body.definition.mass ?? 1; body.velocity = Object.freeze({ x: body.velocity.x + impulse.x / mass, y: body.velocity.y + impulse.y / mass, z: body.velocity.z + impulse.z / mass }); },
    setKinematicPosition(rawId, rawPosition): void { active(disposed, "General Physics runtime"); const body = requireBody(rawId); if (body.definition.kind !== "kinematic") throw new TypeError("Position control requires a kinematic body"); body.position = vector(rawPosition, "Kinematic position"); },
    step(rawTick, rawDt): readonly PhysicsContactEvent[] {
      active(disposed, "General Physics runtime"); tick(rawTick, "Physics tick"); const dt = positive(rawDt, "Physics dt"); const previous = new Map<string, GenreVector3>();
      for (const body of bodies.values()) if (body.definition.kind === "dynamic") { previous.set(body.definition.id, body.position); const mass = body.definition.mass ?? 1; const scale = body.definition.gravityScale ?? 1; body.velocity = Object.freeze({ x: body.velocity.x + (gravity.x * scale + body.force.x / mass) * dt, y: body.velocity.y + (gravity.y * scale + body.force.y / mass) * dt, z: body.velocity.z + (gravity.z * scale + body.force.z / mass) * dt }); body.position = Object.freeze({ x: body.position.x + body.velocity.x * dt, y: body.position.y + body.velocity.y * dt, z: body.position.z + body.velocity.z * dt }); body.force = Object.freeze({ x: 0, y: 0, z: 0 }); }
      const ordered = [...bodies.values()].sort((a, b) => compare(a.definition.id, b.definition.id)); const next = new Map<string, { a: string; b: string; sensor: boolean }>(); const events: PhysicsContactEvent[] = [];
      for (let i = 0; i < ordered.length; i += 1) for (let j = i + 1; j < ordered.length; j += 1) { const a = ordered[i]; const b = ordered[j]; if (a === undefined || b === undefined || ((a.definition.mask ?? 0x7fffffff) & (b.definition.layer ?? 1)) === 0 || ((b.definition.mask ?? 0x7fffffff) & (a.definition.layer ?? 1)) === 0 || !overlap(a, b)) continue; const key = `${a.definition.id}\0${b.definition.id}`; const sensor = (a.definition.sensor ?? false) || (b.definition.sensor ?? false); next.set(key, { a: a.definition.id, b: b.definition.id, sensor }); events.push(Object.freeze({ kind: contacts.has(key) ? "stay" : "enter", bodyAId: a.definition.id, bodyBId: b.definition.id, sensor, tick: rawTick })); if (!sensor) for (const body of [a, b]) if (body.definition.kind === "dynamic") { body.position = previous.get(body.definition.id) ?? body.position; body.velocity = Object.freeze({ x: 0, y: 0, z: 0 }); } }
      for (const [key, pair] of contacts) if (!next.has(key)) events.push(Object.freeze({ kind: "exit", bodyAId: pair.a, bodyBId: pair.b, sensor: pair.sensor, tick: rawTick })); contacts = next; stepCount += 1; return Object.freeze(events);
    },
    raycast(rawOrigin, rawDirection, rawMaximum, rawMask = 0x7fffffff): PhysicsRayHit | undefined { active(disposed, "General Physics runtime"); const origin = vector(rawOrigin, "Ray origin"); const direction = vector(rawDirection, "Ray direction"); const length = Math.hypot(direction.x, direction.y, direction.z); if (length === 0) throw new TypeError("Ray direction must be non-zero"); const maximum = positive(rawMaximum, "Ray maximum distance"); const mask = bits(rawMask, 0x7fffffff, "Ray mask"); let best: PhysicsRayHit | undefined; for (const body of bodies.values()) { if ((mask & (body.definition.layer ?? 1)) === 0) continue; const dx = direction.x / length; const dy = direction.y / length; const dz = direction.z / length; let near = 0; let far = maximum; const axes: readonly (readonly [number, number, number, number])[] = [[origin.x, dx, body.position.x, body.definition.halfExtents.x], [origin.y, dy, body.position.y, body.definition.halfExtents.y], [origin.z, dz, body.position.z, body.definition.halfExtents.z]]; for (const [o, d, c, h] of axes) { if (Math.abs(d) < 1e-12) { if (o < c - h || o > c + h) { far = -1; break; } } else { const one = (c - h - o) / d; const two = (c + h - o) / d; near = Math.max(near, Math.min(one, two)); far = Math.min(far, Math.max(one, two)); } } if (near <= far && near <= maximum && (best === undefined || near < best.distance)) best = Object.freeze({ bodyId: body.definition.id, distance: near, point: Object.freeze({ x: origin.x + dx * near, y: origin.y + dy * near, z: origin.z + dz * near }) }); } return best; },
    overlapBox(rawCenter, rawHalf, rawMask = 0x7fffffff): readonly string[] { active(disposed, "General Physics runtime"); const center = vector(rawCenter, "Overlap center"); const half = vector(rawHalf, "Overlap halfExtents"); if (half.x <= 0 || half.y <= 0 || half.z <= 0) throw new TypeError("Overlap halfExtents must be positive"); const mask = bits(rawMask, 0x7fffffff, "Overlap mask"); return Object.freeze([...bodies.values()].filter((body) => (mask & (body.definition.layer ?? 1)) !== 0 && Math.abs(center.x - body.position.x) <= half.x + body.definition.halfExtents.x && Math.abs(center.y - body.position.y) <= half.y + body.definition.halfExtents.y && Math.abs(center.z - body.position.z) <= half.z + body.definition.halfExtents.z).map((body) => body.definition.id).sort(compare)); },
    inspect(): GeneralPhysicsInspection { return Object.freeze({ disposed, bodies: Object.freeze([...bodies.values()].map(bodyState).sort((a, b) => compare(a.id, b.id))), activeContactCount: contacts.size, stepCount }); },
    dispose(): void { if (!disposed) { disposed = true; bodies.clear(); contacts.clear(); } },
  });
  return runtime;
}

// Projectile
export interface ProjectileDefinition { readonly id: string; readonly speed: number; readonly lifetimeTicks: number; readonly radius?: number; }
export interface ProjectileState { readonly id: string; readonly definitionId: string; readonly sourceId: string; readonly position: GenreVector3; readonly velocity: GenreVector3; readonly firedTick: number; readonly expiresTick: number; }
export interface ProjectileEvent { readonly kind: "fired" | "moved" | "hit" | "expired"; readonly projectile: ProjectileState; readonly targetId: string | null; readonly tick: number; }
export interface ProjectileRuntime { readonly disposed: boolean; fire(definitionId: string, sourceId: string, position: GenreVector3, direction: GenreVector3, firedTick: number, projectileId?: string): ProjectileState; step(stepTick: number, dtSeconds: number): readonly ProjectileEvent[]; inspect(): Readonly<{ disposed: boolean; projectiles: readonly ProjectileState[]; nextOrdinal: number }>; dispose(): void; }
export function createProjectileRuntime(definitionsInput: readonly ProjectileDefinition[], queryHit: (projectile: ProjectileState, nextPosition: GenreVector3) => string | null = () => null): ProjectileRuntime {
  if (!Array.isArray(definitionsInput) || typeof queryHit !== "function") throw new TypeError("Projectile options are invalid"); const definitions = new Map<string, ProjectileDefinition>(); for (const raw of definitionsInput) { const key = id(raw.id, "Projectile definition ID"); if (definitions.has(key)) throw new TypeError(`Duplicate projectile definition: ${key}`); definitions.set(key, Object.freeze({ id: key, speed: positive(raw.speed, "Projectile speed"), lifetimeTicks: tick(raw.lifetimeTicks, "Projectile lifetime"), radius: positive(raw.radius ?? 0.05, "Projectile radius") })); }
  const projectiles = new Map<string, ProjectileState>(); let nextOrdinal = 1; let disposed = false;
  const runtime = Object.freeze<ProjectileRuntime>({ get disposed() { return disposed; }, fire(rawDefinitionId, rawSourceId, rawPosition, rawDirection, firedTick, rawProjectileId): ProjectileState { active(disposed, "Projectile runtime"); tick(firedTick, "Projectile fired tick"); const definitionId = id(rawDefinitionId, "Projectile definition ID"); const definition = definitions.get(definitionId); if (definition === undefined) throw new RangeError(`Unknown projectile: ${definitionId}`); const direction = vector(rawDirection, "Projectile direction"); const length = Math.hypot(direction.x, direction.y, direction.z); if (length === 0) throw new TypeError("Projectile direction must be non-zero"); const projectileId = rawProjectileId === undefined ? `${definitionId}:${nextOrdinal++}` : id(rawProjectileId, "Projectile ID"); if (projectiles.has(projectileId)) throw new TypeError(`Duplicate projectile: ${projectileId}`); const state = Object.freeze({ id: projectileId, definitionId, sourceId: id(rawSourceId, "Projectile source ID"), position: vector(rawPosition, "Projectile position"), velocity: Object.freeze({ x: direction.x / length * definition.speed, y: direction.y / length * definition.speed, z: direction.z / length * definition.speed }), firedTick, expiresTick: firedTick + definition.lifetimeTicks }); projectiles.set(projectileId, state); return state; }, step(rawTick, rawDt): readonly ProjectileEvent[] { active(disposed, "Projectile runtime"); tick(rawTick, "Projectile tick"); const dt = positive(rawDt, "Projectile dt"); const events: ProjectileEvent[] = []; for (const current of [...projectiles.values()].sort((a, b) => compare(a.id, b.id))) { if (rawTick >= current.expiresTick) { projectiles.delete(current.id); events.push(Object.freeze({ kind: "expired", projectile: current, targetId: null, tick: rawTick })); continue; } const nextPosition = Object.freeze({ x: current.position.x + current.velocity.x * dt, y: current.position.y + current.velocity.y * dt, z: current.position.z + current.velocity.z * dt }); const targetId = queryHit(current, nextPosition); const next = Object.freeze({ ...current, position: nextPosition }); if (targetId !== null) { projectiles.delete(current.id); events.push(Object.freeze({ kind: "hit", projectile: next, targetId: id(targetId, "Projectile target ID"), tick: rawTick })); } else { projectiles.set(current.id, next); events.push(Object.freeze({ kind: "moved", projectile: next, targetId: null, tick: rawTick })); } } return Object.freeze(events); }, inspect() { return Object.freeze({ disposed, projectiles: Object.freeze([...projectiles.values()].sort((a, b) => compare(a.id, b.id))), nextOrdinal }); }, dispose() { if (!disposed) { disposed = true; projectiles.clear(); } } });
  return runtime;
}

// Inventory
export interface InventoryItemDefinition { readonly id: string; readonly maximumStack: number; }
export interface InventorySlot { readonly itemId: string; readonly count: number; }
export type InventoryFailureCode = "unknown-container" | "unknown-item" | "insufficient-items" | "capacity-exceeded" | "same-container";
export type InventoryOutcome = Readonly<{ readonly ok: true; readonly changed: number }> | Readonly<{ readonly ok: false; readonly code: InventoryFailureCode }>;
export interface InventoryRuntime { readonly disposed: boolean; createContainer(id: string, capacitySlots: number): void; add(containerId: string, itemId: string, count: number): InventoryOutcome; remove(containerId: string, itemId: string, count: number): InventoryOutcome; transfer(fromId: string, toId: string, itemId: string, count: number): InventoryOutcome; snapshot(): Readonly<Record<string, readonly InventorySlot[]>>; dispose(): void; }
export function createInventoryRuntime(rawDefinitions: readonly InventoryItemDefinition[]): InventoryRuntime {
  if (!Array.isArray(rawDefinitions)) throw new TypeError("Inventory definitions must be an array"); const definitions = new Map<string, number>(); for (const raw of rawDefinitions) { const itemId = id(raw.id, "Item ID"); if (definitions.has(itemId)) throw new TypeError(`Duplicate item: ${itemId}`); definitions.set(itemId, positiveInteger(raw.maximumStack, "Maximum stack")); }
  const containers = new Map<string, { capacity: number; counts: Map<string, number> }>(); let disposed = false; const fail = (code: InventoryFailureCode): InventoryOutcome => Object.freeze({ ok: false, code });
  function find(rawContainerId: string) { return containers.get(id(rawContainerId, "Container ID")); }
  function room(container: { capacity: number; counts: Map<string, number> }, itemId: string): number { const maximum = definitions.get(itemId) ?? 0; const current = container.counts.get(itemId) ?? 0; const usedSlots = [...container.counts].reduce((total, [storedItemId, count]) => total + Math.ceil(count / (definitions.get(storedItemId) ?? 1)), 0); const currentSlots = current === 0 ? 0 : Math.ceil(current / maximum); const availableSlots = Math.max(0, container.capacity - (usedSlots - currentSlots)); return Math.max(0, availableSlots * maximum - current); }
  const runtime = Object.freeze<InventoryRuntime>({ get disposed() { return disposed; }, createContainer(rawId, rawCapacity): void { active(disposed, "Inventory runtime"); const containerId = id(rawId, "Container ID"); if (containers.has(containerId)) throw new TypeError(`Duplicate container: ${containerId}`); containers.set(containerId, { capacity: positiveInteger(rawCapacity, "Container capacity"), counts: new Map() }); }, add(rawContainerId, rawItemId, rawCount): InventoryOutcome { active(disposed, "Inventory runtime"); const container = find(rawContainerId); if (container === undefined) return fail("unknown-container"); const itemId = id(rawItemId, "Item ID"); if (!definitions.has(itemId)) return fail("unknown-item"); const count = positiveInteger(rawCount, "Item count"); if (room(container, itemId) < count) return fail("capacity-exceeded"); container.counts.set(itemId, (container.counts.get(itemId) ?? 0) + count); return Object.freeze({ ok: true, changed: count }); }, remove(rawContainerId, rawItemId, rawCount): InventoryOutcome { active(disposed, "Inventory runtime"); const container = find(rawContainerId); if (container === undefined) return fail("unknown-container"); const itemId = id(rawItemId, "Item ID"); if (!definitions.has(itemId)) return fail("unknown-item"); const count = positiveInteger(rawCount, "Item count"); const current = container.counts.get(itemId) ?? 0; if (current < count) return fail("insufficient-items"); if (current === count) container.counts.delete(itemId); else container.counts.set(itemId, current - count); return Object.freeze({ ok: true, changed: count }); }, transfer(rawFrom, rawTo, rawItem, rawCount): InventoryOutcome { active(disposed, "Inventory runtime"); const fromId = id(rawFrom, "Source container ID"); const toId = id(rawTo, "Target container ID"); if (fromId === toId) return fail("same-container"); const from = containers.get(fromId); const to = containers.get(toId); if (from === undefined || to === undefined) return fail("unknown-container"); const itemId = id(rawItem, "Item ID"); if (!definitions.has(itemId)) return fail("unknown-item"); const count = positiveInteger(rawCount, "Item count"); if ((from.counts.get(itemId) ?? 0) < count) return fail("insufficient-items"); if (room(to, itemId) < count) return fail("capacity-exceeded"); const remaining = (from.counts.get(itemId) ?? 0) - count; if (remaining === 0) from.counts.delete(itemId); else from.counts.set(itemId, remaining); to.counts.set(itemId, (to.counts.get(itemId) ?? 0) + count); return Object.freeze({ ok: true, changed: count }); }, snapshot() { return Object.freeze(Object.fromEntries([...containers].sort(([a], [b]) => compare(a, b)).map(([containerId, container]) => [containerId, Object.freeze([...container.counts].sort(([a], [b]) => compare(a, b)).map(([itemId, count]) => Object.freeze({ itemId, count })))]))); }, dispose() { if (!disposed) { disposed = true; containers.clear(); } } });
  return runtime;
}
function positiveInteger(value: number, label: string): number { if (!Number.isSafeInteger(value) || value <= 0) throw new TypeError(`${label} must be a positive safe integer`); return value; }

// Ability / Skill
export interface AbilityDefinition { readonly id: string; readonly cooldownTicks: number; readonly castTicks?: number; }
export interface AbilityEvent { readonly kind: "started" | "completed" | "cancelled" | "rejected"; readonly actorId: string; readonly abilityId: string; readonly tick: number; readonly code: "cooldown" | "cost-rejected" | "already-casting" | null; }
export interface AbilityRuntime { readonly disposed: boolean; request(actorId: string, abilityId: string, requestTick: number): void; cancel(actorId: string, cancelTick: number): boolean; step(stepTick: number): readonly AbilityEvent[]; inspect(): Readonly<{ disposed: boolean; pendingCount: number; casting: readonly Readonly<{ actorId: string; abilityId: string; completesTick: number }>[] }>; dispose(): void; }
export function createAbilityRuntime(rawDefinitions: readonly AbilityDefinition[], hooks: Readonly<{ readonly validateCost?: (actorId: string, abilityId: string) => boolean; readonly consumeCost?: (actorId: string, abilityId: string) => void }> = {}): AbilityRuntime {
  if (!Array.isArray(rawDefinitions) || typeof hooks !== "object" || hooks === null || (hooks.validateCost !== undefined && typeof hooks.validateCost !== "function") || (hooks.consumeCost !== undefined && typeof hooks.consumeCost !== "function")) throw new TypeError("Ability options are invalid"); const definitions = new Map<string, { cooldown: number; cast: number }>(); for (const raw of rawDefinitions) { const abilityId = id(raw.id, "Ability ID"); if (definitions.has(abilityId)) throw new TypeError(`Duplicate ability: ${abilityId}`); definitions.set(abilityId, { cooldown: tick(raw.cooldownTicks, "Ability cooldown"), cast: tick(raw.castTicks ?? 0, "Ability cast") }); }
  const pending: { actorId: string; abilityId: string; tick: number }[] = []; const casting = new Map<string, { abilityId: string; completesTick: number }>(); const cooldowns = new Map<string, number>(); let disposed = false;
  const runtime = Object.freeze<AbilityRuntime>({ get disposed() { return disposed; }, request(rawActor, rawAbility, rawTick): void { active(disposed, "Ability runtime"); pending.push({ actorId: id(rawActor, "Ability actor ID"), abilityId: id(rawAbility, "Ability ID"), tick: tick(rawTick, "Ability request tick") }); }, cancel(rawActor, rawTick): boolean { active(disposed, "Ability runtime"); const actorId = id(rawActor, "Ability actor ID"); tick(rawTick, "Ability cancel tick"); return casting.delete(actorId); }, step(rawTick): readonly AbilityEvent[] { active(disposed, "Ability runtime"); tick(rawTick, "Ability tick"); const events: AbilityEvent[] = []; for (const [actorId, cast] of [...casting].sort(([a], [b]) => compare(a, b))) if (rawTick >= cast.completesTick) { casting.delete(actorId); events.push(Object.freeze({ kind: "completed", actorId, abilityId: cast.abilityId, tick: rawTick, code: null })); } const requests = pending.splice(0).sort((a, b) => a.tick - b.tick || compare(a.actorId, b.actorId) || compare(a.abilityId, b.abilityId)); for (const request of requests) { const definition = definitions.get(request.abilityId); if (definition === undefined) throw new RangeError(`Unknown ability: ${request.abilityId}`); let code: AbilityEvent["code"] = null; const key = `${request.actorId}\0${request.abilityId}`; if (casting.has(request.actorId)) code = "already-casting"; else if ((cooldowns.get(key) ?? 0) > rawTick) code = "cooldown"; else if (!(hooks.validateCost?.(request.actorId, request.abilityId) ?? true)) code = "cost-rejected"; if (code !== null) { events.push(Object.freeze({ kind: "rejected", actorId: request.actorId, abilityId: request.abilityId, tick: rawTick, code })); continue; } hooks.consumeCost?.(request.actorId, request.abilityId); cooldowns.set(key, rawTick + definition.cooldown + 1); events.push(Object.freeze({ kind: "started", actorId: request.actorId, abilityId: request.abilityId, tick: rawTick, code: null })); if (definition.cast === 0) events.push(Object.freeze({ kind: "completed", actorId: request.actorId, abilityId: request.abilityId, tick: rawTick, code: null })); else casting.set(request.actorId, { abilityId: request.abilityId, completesTick: rawTick + definition.cast }); } return Object.freeze(events); }, inspect() { return Object.freeze({ disposed, pendingCount: pending.length, casting: Object.freeze([...casting].sort(([a], [b]) => compare(a, b)).map(([actorId, cast]) => Object.freeze({ actorId, ...cast }))) }); }, dispose() { if (!disposed) { disposed = true; pending.length = 0; casting.clear(); cooldowns.clear(); } } });
  return runtime;
}

// Simple AI / Navigation
export interface AiAgentState { readonly id: string; readonly behavior: string; readonly position: GenreVector3; readonly targetId: string | null; readonly waypointCount: number; }
export interface SimpleAiRuntime { readonly disposed: boolean; register(id: string, position: GenreVector3, speed: number): AiAgentState; setWaypoints(agentId: string, waypoints: readonly GenreVector3[]): void; step(stepTick: number, dtSeconds: number): readonly AiAgentState[]; inspect(): Readonly<{ disposed: boolean; agents: readonly AiAgentState[]; stepCount: number }>; dispose(): void; }
export function createSimpleAiRuntime(hooks: Readonly<{ readonly selectBehavior?: (agent: AiAgentState, tick: number) => string; readonly selectTarget?: (agent: AiAgentState, tick: number) => string | null }> = {}): SimpleAiRuntime {
  if (typeof hooks !== "object" || hooks === null || (hooks.selectBehavior !== undefined && typeof hooks.selectBehavior !== "function") || (hooks.selectTarget !== undefined && typeof hooks.selectTarget !== "function")) throw new TypeError("Simple AI hooks are invalid"); const agents = new Map<string, { position: GenreVector3; speed: number; behavior: string; targetId: string | null; waypoints: GenreVector3[] }>(); let stepCount = 0; let disposed = false; function state(agentId: string, agent: { position: GenreVector3; behavior: string; targetId: string | null; waypoints: GenreVector3[] }): AiAgentState { return Object.freeze({ id: agentId, behavior: agent.behavior, position: agent.position, targetId: agent.targetId, waypointCount: agent.waypoints.length }); }
  const runtime = Object.freeze<SimpleAiRuntime>({ get disposed() { return disposed; }, register(rawId, rawPosition, rawSpeed): AiAgentState { active(disposed, "Simple AI runtime"); const agentId = id(rawId, "AI agent ID"); if (agents.has(agentId)) throw new TypeError(`Duplicate AI agent: ${agentId}`); const agent = { position: vector(rawPosition, "AI position"), speed: positive(rawSpeed, "AI speed"), behavior: "idle", targetId: null, waypoints: [] }; agents.set(agentId, agent); return state(agentId, agent); }, setWaypoints(rawId, rawWaypoints): void { active(disposed, "Simple AI runtime"); const agentId = id(rawId, "AI agent ID"); const agent = agents.get(agentId); if (agent === undefined) throw new RangeError(`Unknown AI agent: ${agentId}`); if (!Array.isArray(rawWaypoints)) throw new TypeError("AI waypoints must be an array"); agent.waypoints = rawWaypoints.map((item) => vector(item, "AI waypoint")); }, step(rawTick, rawDt): readonly AiAgentState[] { active(disposed, "Simple AI runtime"); tick(rawTick, "AI tick"); const dt = positive(rawDt, "AI dt"); const results: AiAgentState[] = []; for (const [agentId, agent] of [...agents].sort(([a], [b]) => compare(a, b))) { const before = state(agentId, agent); agent.behavior = id(hooks.selectBehavior?.(before, rawTick) ?? (agent.waypoints.length > 0 ? "follow-path" : "idle"), "AI behavior"); const target = hooks.selectTarget?.(before, rawTick) ?? null; agent.targetId = target === null ? null : id(target, "AI target ID"); const waypoint = agent.waypoints[0]; if (waypoint !== undefined) { const dx = waypoint.x - agent.position.x; const dy = waypoint.y - agent.position.y; const dz = waypoint.z - agent.position.z; const distance = Math.hypot(dx, dy, dz); const movement = agent.speed * dt; if (distance <= movement) { agent.position = waypoint; agent.waypoints.shift(); } else agent.position = Object.freeze({ x: agent.position.x + dx / distance * movement, y: agent.position.y + dy / distance * movement, z: agent.position.z + dz / distance * movement }); } results.push(state(agentId, agent)); } stepCount += 1; return Object.freeze(results); }, inspect() { return Object.freeze({ disposed, agents: Object.freeze([...agents].sort(([a], [b]) => compare(a, b)).map(([agentId, agent]) => state(agentId, agent))), stepCount }); }, dispose() { if (!disposed) { disposed = true; agents.clear(); } } });
  return runtime;
}

// Save / Load
export type SaveValue = null | boolean | number | string | readonly SaveValue[] | Readonly<{ readonly [key: string]: SaveValue }>;
export interface SaveDocument { readonly schemaVersion: number; readonly data: SaveValue; }
export interface SaveAdapter { write(slot: string, document: SaveDocument): void | Promise<void>; read(slot: string): SaveDocument | undefined | Promise<SaveDocument | undefined>; remove(slot: string): void | Promise<void>; dispose(): void | Promise<void>; }
export type SaveLoadOutcome = Readonly<{ readonly ok: true; readonly document: SaveDocument }> | Readonly<{ readonly ok: false; readonly code: "not-found" | "future-version" | "migration-failed" | "validation-failed" | "adapter-failed" }>;
export interface SaveLoadRuntime { readonly disposed: boolean; save(slot: string): Promise<SaveLoadOutcome>; load(slot: string): Promise<SaveLoadOutcome>; remove(slot: string): Promise<boolean>; dispose(): Promise<void>; }
function saveValue(raw: unknown, depth = 0): SaveValue { if (depth > 32) throw new TypeError("Save value nesting exceeds 32"); if (raw === null || typeof raw === "boolean" || typeof raw === "string") return raw; if (typeof raw === "number") return number(raw, "Save number"); if (Array.isArray(raw)) return Object.freeze(raw.map((item) => saveValue(item, depth + 1))); if (typeof raw === "object" && raw !== null && (Object.getPrototypeOf(raw) === Object.prototype || Object.getPrototypeOf(raw) === null)) { const result: Record<string, SaveValue> = {}; for (const [key, value] of Object.entries(raw)) result[id(key, "Save key")] = saveValue(value, depth + 1); return Object.freeze(result); } throw new TypeError("Save data must be JSON-like"); }
export function createInMemorySaveAdapter(): SaveAdapter & { inspect(): Readonly<{ disposed: boolean; slots: readonly string[] }> } { const slots = new Map<string, SaveDocument>(); let disposed = false; const adapter = Object.freeze<SaveAdapter & { inspect(): Readonly<{ disposed: boolean; slots: readonly string[] }> }>({ write(slot, document) { active(disposed, "Save adapter"); slots.set(id(slot, "Save slot"), document); }, read(slot) { active(disposed, "Save adapter"); return slots.get(id(slot, "Save slot")); }, remove(slot) { active(disposed, "Save adapter"); slots.delete(id(slot, "Save slot")); }, inspect() { return Object.freeze({ disposed, slots: Object.freeze([...slots.keys()].sort(compare)) }); }, dispose() { if (!disposed) { disposed = true; slots.clear(); } } }); return adapter; }
export function createSaveLoadRuntime(options: Readonly<{ readonly currentVersion: number; readonly capture: () => SaveValue; readonly restore: (data: SaveValue) => void; readonly validate?: (data: SaveValue) => boolean; readonly migrations?: Readonly<Record<number, (data: SaveValue) => SaveValue>>; readonly adapter: SaveAdapter }>): SaveLoadRuntime {
  if (typeof options !== "object" || options === null || !Number.isSafeInteger(options.currentVersion) || options.currentVersion <= 0 || typeof options.capture !== "function" || typeof options.restore !== "function" || typeof options.adapter !== "object" || options.adapter === null) throw new TypeError("Save Load options are invalid"); let disposed = false; const currentVersion = options.currentVersion;
  const runtime = Object.freeze<SaveLoadRuntime>({ get disposed() { return disposed; }, async save(rawSlot): Promise<SaveLoadOutcome> { active(disposed, "Save Load runtime"); const slot = id(rawSlot, "Save slot"); let saveDocument: SaveDocument; try { saveDocument = Object.freeze({ schemaVersion: currentVersion, data: saveValue(options.capture()) }); if (!(options.validate?.(saveDocument.data) ?? true)) return Object.freeze({ ok: false, code: "validation-failed" }); await options.adapter.write(slot, saveDocument); } catch { return Object.freeze({ ok: false, code: "adapter-failed" }); } return Object.freeze({ ok: true, document: saveDocument }); }, async load(rawSlot): Promise<SaveLoadOutcome> { active(disposed, "Save Load runtime"); let raw: SaveDocument | undefined; try { raw = await options.adapter.read(id(rawSlot, "Save slot")); } catch { return Object.freeze({ ok: false, code: "adapter-failed" }); } if (raw === undefined) return Object.freeze({ ok: false, code: "not-found" }); if (!Number.isSafeInteger(raw.schemaVersion) || raw.schemaVersion <= 0) return Object.freeze({ ok: false, code: "validation-failed" }); if (raw.schemaVersion > currentVersion) return Object.freeze({ ok: false, code: "future-version" }); let data: SaveValue; try { data = saveValue(raw.data); for (let version = raw.schemaVersion; version < currentVersion; version += 1) { const migrate = options.migrations?.[version]; if (migrate === undefined) return Object.freeze({ ok: false, code: "migration-failed" }); data = saveValue(migrate(data)); } } catch { return Object.freeze({ ok: false, code: "migration-failed" }); } if (!(options.validate?.(data) ?? true)) return Object.freeze({ ok: false, code: "validation-failed" }); const saveDocument = Object.freeze({ schemaVersion: currentVersion, data }); try { options.restore(data); } catch { return Object.freeze({ ok: false, code: "validation-failed" }); } return Object.freeze({ ok: true, document: saveDocument }); }, async remove(rawSlot): Promise<boolean> { active(disposed, "Save Load runtime"); try { const slot = id(rawSlot, "Save slot"); if (await options.adapter.read(slot) === undefined) return false; await options.adapter.remove(slot); return true; } catch { return false; } }, async dispose(): Promise<void> { if (!disposed) { disposed = true; await options.adapter.dispose(); } } });
  return runtime;
}
